package doctor

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/hilather/mount-wrapper/internal/config"
	"github.com/hilather/mount-wrapper/internal/paths"
	"github.com/hilather/mount-wrapper/internal/platform"
)

// BuildSystemdDropin generates systemd drop-in unit content for source/stage paths.
//
// Extends ReadOnlyPaths / ReadWritePaths for configured source directories and
// archives_dir, and allows /dev/fuse.
func BuildSystemdDropin(cfg *config.Config) string {
	if cfg == nil {
		cfg = &config.Config{}
	}

	readOnly := make([]string, 0)
	readWrite := []string{
		"/var/lib/mount-wrapper",
		"/var/log/mount-wrapper",
		"/run/mount-wrapper",
	}

	// Prefer platform defaults when config paths match the Linux layout.
	if dp := platform.LinuxDefaultPaths(); dp.MountRoot != "" {
		// Already covered by /var/lib/mount-wrapper parent; keep explicit data roots.
		_ = dp
	}

	for _, raw := range cfg.SourceDirs {
		mapped, err := paths.ToWSLPath(raw, &paths.ToWSLOpts{})
		if err != nil {
			continue
		}
		if !containsString(readOnly, mapped) {
			readOnly = append(readOnly, mapped)
		}
		// Also allow /mnt/<letter> when mapped under automount.
		parts := splitPath(mapped)
		if len(parts) >= 2 && parts[0] == "mnt" && len(parts[1]) == 1 {
			driveRoot := "/mnt/" + parts[1]
			if !containsString(readOnly, driveRoot) {
				readOnly = append(readOnly, driveRoot)
			}
		}
	}

	if strings.TrimSpace(cfg.ArchivesDir) != "" {
		archived, err := paths.ToWSLPath(cfg.ArchivesDir, &paths.ToWSLOpts{})
		if err == nil && !containsString(readWrite, archived) {
			readWrite = append(readWrite, archived)
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by mount-wrapper doctor --fix-systemd\n")
	b.WriteString("# Extends ReadOnlyPaths/ReadWritePaths for configured source directories.\n")
	b.WriteString("[Service]\n")
	b.WriteString("DeviceAllow=/dev/fuse rw\n")
	if len(readOnly) > 0 {
		b.WriteString("ReadOnlyPaths=" + strings.Join(readOnly, " ") + "\n")
	}
	if len(readWrite) > 0 {
		b.WriteString("ReadWritePaths=" + strings.Join(readWrite, " ") + "\n")
	}
	return b.String()
}

// ApplyFixSystemd writes the systemd drop-in to dropinPath.
// Returns (ok, message). opts may be nil for production I/O.
func ApplyFixSystemd(cfg *config.Config, dropinPath string, opts *Options) (bool, string) {
	if dropinPath == "" {
		dropinPath = DefaultSystemdDropinFile
	}
	content := BuildSystemdDropin(cfg)

	mkdir := os.MkdirAll
	write := defaultWriteFile
	if opts != nil {
		mkdir = opts.mkdirAll()
		write = opts.writeFile()
	}

	parent := filepath.Dir(dropinPath)
	if err := mkdir(parent, 0o755); err != nil {
		return false, "cannot write " + dropinPath + ": " + err.Error()
	}
	if err := write(dropinPath, []byte(content), 0o644); err != nil {
		return false, "cannot write " + dropinPath + ": " + err.Error()
	}
	return true, "wrote " + dropinPath
}

// splitPath splits an absolute Unix path into components without the leading empty.
func splitPath(p string) []string {
	p = filepath.ToSlash(p)
	p = strings.Trim(p, "/")
	if p == "" {
		return nil
	}
	return strings.Split(p, "/")
}
