package doctor

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/hilather/mount-wrapper/internal/config"
	"github.com/hilather/mount-wrapper/internal/paths"
)

// BuildSystemdDropin generates systemd drop-in unit content for source/stage paths.
//
// Extends ReadOnlyPaths for configured source directories and ReadWritePaths for
// archives_dir plus custom absolute data roots (mount_root, index_dir, overlay_dir,
// convert_7z_cache_dir, archiveconverter_output_dir) when not already covered by
// the packaged bases (/var/lib/mount-wrapper, /var/log/mount-wrapper, /run/mount-wrapper).
// Paths are deduped; source_dirs stay read-only.
func BuildSystemdDropin(cfg *config.Config) string {
	if cfg == nil {
		cfg = &config.Config{}
	}

	readOnly := make([]string, 0)
	readWrite := []string{
		"/var/lib/mount-wrapper",
		"/var/log/mount-wrapper",
		"/run/mount-wrapper",
	}

	for _, raw := range cfg.SourceDirs {
		mapped, err := paths.ToWSLPath(raw, &paths.ToWSLOpts{})
		if err != nil {
			continue
		}
		if !containsString(readOnly, mapped) {
			readOnly = append(readOnly, mapped)
		}
		// Also allow /mnt/<letter> when mapped under automount.
		parts := splitPath(mapped)
		if len(parts) >= 2 && parts[0] == "mnt" && len(parts[1]) == 1 {
			driveRoot := "/mnt/" + parts[1]
			if !containsString(readOnly, driveRoot) {
				readOnly = append(readOnly, driveRoot)
			}
		}
	}

	if strings.TrimSpace(cfg.ArchivesDir) != "" {
		appendUncoveredPath(&readWrite, cfg.ArchivesDir)
	}

	// Custom data roots: RW when absolute and not already covered by a base or
	// earlier entry (defaults under /var/lib/mount-wrapper are skipped).
	for _, raw := range []string{
		cfg.MountRoot,
		cfg.IndexDir,
		cfg.OverlayDir,
		cfg.Convert7zCacheDir,
		cfg.ArchiveconverterOutputDir,
	} {
		appendUncoveredPath(&readWrite, raw)
	}

	var b strings.Builder
	b.WriteString("# Generated by mount-wrapper doctor --fix-systemd\n")
	b.WriteString("# Extends ReadOnlyPaths/ReadWritePaths for configured source and data directories.\n")
	b.WriteString("[Service]\n")
	b.WriteString("DeviceAllow=/dev/fuse rw\n")
	if len(readOnly) > 0 {
		b.WriteString("ReadOnlyPaths=" + strings.Join(readOnly, " ") + "\n")
	}
	if len(readWrite) > 0 {
		b.WriteString("ReadWritePaths=" + strings.Join(readWrite, " ") + "\n")
	}
	return b.String()
}

// ApplyFixSystemd writes the systemd drop-in to dropinPath.
// Returns (ok, message). opts may be nil for production I/O.
func ApplyFixSystemd(cfg *config.Config, dropinPath string, opts *Options) (bool, string) {
	if dropinPath == "" {
		dropinPath = DefaultSystemdDropinFile
	}
	content := BuildSystemdDropin(cfg)

	mkdir := os.MkdirAll
	write := defaultWriteFile
	if opts != nil {
		mkdir = opts.mkdirAll()
		write = opts.writeFile()
	}

	parent := filepath.Dir(dropinPath)
	if err := mkdir(parent, 0o755); err != nil {
		return false, "cannot write " + dropinPath + ": " + err.Error()
	}
	if err := write(dropinPath, []byte(content), 0o644); err != nil {
		return false, "cannot write " + dropinPath + ": " + err.Error()
	}
	return true, "wrote " + dropinPath
}

// appendUncoveredPath maps raw via ToWSLPath and appends it to list when the
// result is an absolute path not already covered by an existing entry.
func appendUncoveredPath(list *[]string, raw string) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return
	}
	mapped, err := paths.ToWSLPath(raw, &paths.ToWSLOpts{})
	if err != nil {
		return
	}
	mapped = filepath.ToSlash(filepath.Clean(mapped))
	if !isAbsoluteUnixPath(mapped) {
		return
	}
	if pathAlreadyCovered(*list, mapped) {
		return
	}
	*list = append(*list, mapped)
}

// pathAlreadyCovered reports whether p equals or is nested under any entry in list.
func pathAlreadyCovered(list []string, p string) bool {
	p = filepath.ToSlash(filepath.Clean(p))
	for _, parent := range list {
		parent = filepath.ToSlash(filepath.Clean(parent))
		if p == parent {
			return true
		}
		if parent != "/" && strings.HasPrefix(p, parent+"/") {
			return true
		}
	}
	return false
}

// isAbsoluteUnixPath reports whether p is an absolute Unix path (/...).
func isAbsoluteUnixPath(p string) bool {
	return strings.HasPrefix(p, "/")
}

// splitPath splits an absolute Unix path into components without the leading empty.
func splitPath(p string) []string {
	p = filepath.ToSlash(p)
	p = strings.Trim(p, "/")
	if p == "" {
		return nil
	}
	return strings.Split(p, "/")
}
