#!/usr/bin/env bash
# Inventory CLI commands for mount-wrapper vs local upstream tarmount-wsl.
# Offline-safe: always emits Go-side inventory; compares when sibling present.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
UPSTREAM="${TARMOUNT_WSL_ROOT:-$ROOT/../tarmount-wsl}"
OUT_DIR="${PARITY_OUT:-$ROOT/tools/parity}"
OUT="$OUT_DIR/cli_surface.md"
mkdir -p "$OUT_DIR"

GO_CMDS=()
# Primary commands from internal/cli (stable surface; do not require a binary build).
while IFS= read -r line; do
  GO_CMDS+=("$line")
done <<'EOF'
version
help
serve
doctor
config show
config set
status
metrics
rescan
retry
mount
unmount
purge
hooks list
hooks status
EOF

# Prefer live --help if binary exists (catches drift).
if [[ -x "$ROOT/bin/mount-wrapper" ]]; then
  LIVE_HELP="$("$ROOT/bin/mount-wrapper" help 2>/dev/null || true)"
elif command -v mount-wrapper >/dev/null 2>&1; then
  LIVE_HELP="$(mount-wrapper help 2>/dev/null || true)"
else
  LIVE_HELP=""
fi

UPSTREAM_NOTE="sibling tarmount-wsl **not found** (default \`../tarmount-wsl\`) — Go-side only."
UP_CMDS=()
if [[ -d "$UPSTREAM" ]]; then
  UPSTREAM_NOTE="compared against sibling \`../tarmount-wsl\` (or \`TARMOUNT_WSL_ROOT\`)"
  CLI_PY=""
  for cand in \
    "$UPSTREAM/src/tarmount_wsl/cli.py" \
    "$UPSTREAM/tarmount_wsl/cli.py"; do
    if [[ -f "$cand" ]]; then
      CLI_PY="$cand"
      break
    fi
  done
  if [[ -n "$CLI_PY" ]] && command -v python3 >/dev/null 2>&1; then
    mapfile -t UP_CMDS < <(python3 - "$CLI_PY" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
# argparse add_parser("name") — flatten nested (config show/set, hooks list/status)
cmds = []
for m in re.finditer(r'add_parser\(\s*["\']([^"\']+)["\']', text):
    cmds.append(m.group(1))
# Heuristic leaf commands
wanted = {
    "serve","status","metrics","rescan","retry","doctor","config","show","set",
    "web","mount","unmount","purge","hooks","list","version",
}
# Reconstruct common two-level surface
flat = []
has = set(cmds)
if "config" in has:
    flat.append("config show")
    flat.append("config set")
if "hooks" in has:
    flat.append("hooks list")
    flat.append("hooks status")
for c in ("version","serve","doctor","status","metrics","rescan","retry","web","mount","unmount","purge"):
    if c in has:
        flat.append(c)
for c in flat:
    print(c)
PY
)
  elif [[ -n "$CLI_PY" ]]; then
    # Fallback grep without python
    mapfile -t UP_CMDS < <(grep -oE 'add_parser\(\s*["'"'"'][^"'"'"']+' "$CLI_PY" \
      | sed -E 's/add_parser\(\s*["'"'"']//' | sort -u)
  else
    UPSTREAM_NOTE="sibling present but cli.py not found under \`$UPSTREAM\`"
  fi
fi

{
  echo "# CLI surface inventory"
  echo
  echo "Generated by \`tools/parity/cli_surface.sh\`."
  echo
  echo "- **mount-wrapper root:** repo root (script: \`tools/parity/cli_surface.sh\`)"
  echo "- **Upstream:** $UPSTREAM_NOTE"
  echo "- **Date (UTC):** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "## mount-wrapper commands"
  echo
  echo "| Command | Notes |"
  echo "|---------|-------|"
  for c in "${GO_CMDS[@]}"; do
    note=""
    case "$c" in
      serve) note="daemon; \`--config\` \`--once\` \`--allow-unauth\`" ;;
      doctor) note="offline; \`--json\` \`--fix-systemd\`" ;;
      "config show"|"config set") note="local or via serve for apply" ;;
      status|metrics|rescan|retry|mount|unmount|purge|"hooks list"|"hooks status") note="requires running serve (control socket)" ;;
      version|help) note="offline" ;;
    esac
    echo "| \`$c\` | $note |"
  done
  echo
  echo "### Intentional differences vs upstream CLI"
  echo
  echo "| Topic | tarmount-wsl | mount-wrapper |"
  echo "|-------|--------------|---------------|"
  echo "| Binary name | \`tarmount-wsl\` | \`mount-wrapper\` only (D2) |"
  echo "| \`web\` command | Sidecar \`tarmount-wsl web\` | **Embedded** in \`serve\` when \`web_enabled\` (D4); no separate web CLI |"
  echo "| serve foreground | \`--foreground\` flag | Process is always foreground |"
  echo "| Hooks env in docs | \`TARMOUNT_*\` | \`MOUNT_WRAPPER_*\` only (D3) |"
  echo
  if [[ ${#UP_CMDS[@]} -gt 0 ]]; then
    echo "## Upstream commands (parsed)"
    echo
    echo "| Command |"
    echo "|---------|"
    for c in "${UP_CMDS[@]}"; do
      echo "| \`$c\` |"
    done
    echo
    echo "## Diff (set-level, normalized)"
    echo
    # Normalize for comparison: web is expected only upstream
    declare -A GO_SET UP_SET
    for c in "${GO_CMDS[@]}"; do GO_SET["$c"]=1; done
    for c in "${UP_CMDS[@]}"; do UP_SET["$c"]=1; done
    echo "### In upstream only"
    echo
    only_up=0
    for c in "${UP_CMDS[@]}"; do
      if [[ -z "${GO_SET[$c]:-}" ]]; then
        echo "- \`$c\`"
        only_up=1
      fi
    done
    [[ $only_up -eq 0 ]] && echo "_(none after normalization)_"
    echo
    echo "### In mount-wrapper only"
    echo
    only_go=0
    for c in "${GO_CMDS[@]}"; do
      if [[ -z "${UP_SET[$c]:-}" ]]; then
        echo "- \`$c\`"
        only_go=1
      fi
    done
    [[ $only_go -eq 0 ]] && echo "_(none)_"
  else
    echo "## Upstream commands"
    echo
    echo "_Skipped — no parseable upstream CLI inventory._"
  fi
  if [[ -n "$LIVE_HELP" ]]; then
    echo
    echo "## Live binary help excerpt"
    echo
    echo '```'
    echo "$LIVE_HELP" | head -n 40
    echo '```'
  fi
} >"$OUT"

echo "Wrote $OUT" >&2
