#!/usr/bin/env bash
# Generate config_keys.md: public keys from internal/config vs optional upstream Config.
# Offline-safe: Go inventory always; upstream diff when sibling + python3 present.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
UPSTREAM="${TARMOUNT_WSL_ROOT:-$ROOT/../tarmount-wsl}"
OUT_DIR="${PARITY_OUT:-$ROOT/tools/parity}"
OUT="$OUT_DIR/config_keys.md"
mkdir -p "$OUT_DIR"

export PATH="${HOME}/.local/go/bin:${PATH}"

GO_KEYS_FILE="$(mktemp)"
UP_KEYS_FILE="$(mktemp)"
trap 'rm -f "$GO_KEYS_FILE" "$UP_KEYS_FILE"' EXIT

# Extract public keys from ToPublicMap via a tiny Go program (no network).
(
  cd "$ROOT"
  go run ./tools/parity/cmd/listkeys >"$GO_KEYS_FILE"
)

UPSTREAM_NOTE="sibling tarmount-wsl **not found** (default \`../tarmount-wsl\`) — Go-side only."
if [[ -d "$UPSTREAM" ]]; then
  UPSTREAM_NOTE="compared against sibling \`../tarmount-wsl\` (or \`TARMOUNT_WSL_ROOT\`)"
  CFG_PY=""
  for cand in \
    "$UPSTREAM/src/tarmount_wsl/config.py" \
    "$UPSTREAM/tarmount_wsl/config.py"; do
    if [[ -f "$cand" ]]; then
      CFG_PY="$cand"
      break
    fi
  done
  if [[ -n "$CFG_PY" ]] && command -v python3 >/dev/null 2>&1; then
    python3 - "$CFG_PY" >"$UP_KEYS_FILE" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
# DEFAULT_PATHS + dataclass field names that look like config keys
keys = set()
for m in re.finditer(r'^\s+([a-z][a-z0-9_]*)\s*:', text, re.M):
    k = m.group(1)
    if k in {"self", "cls", "return", "key", "default", "min_value", "try", "out", "raw", "else"}:
        continue
    if k.startswith("_"):
        continue
    keys.add(k)
# Prefer to_public / DEFAULTS string keys if present
for m in re.finditer(r'["\']([a-z][a-z0-9_]*)["\']\s*:', text):
    k = m.group(1)
    if k in keys or k.endswith("_seconds") or k.startswith("archive") or k.startswith("convert") \
       or k.startswith("ratarmount") or k.startswith("hook") or k.startswith("web") \
       or k in {"source_dirs","mount_root","index_dir","overlay_dir","state_db","log_level","version"}:
        keys.add(k)
# Drop internal non-public helpers commonly left in the file
for drop in ("config_path", "unknown_keys", "raw", "key", "default", "min_value",
             "try", "extra_args", "out", "ac_threads", "ac_nested_concurrency", "else"):
    keys.discard(drop)
for k in sorted(keys):
    print(k)
PY
  else
    UPSTREAM_NOTE="sibling present but could not parse config.py (need python3)"
    : >"$UP_KEYS_FILE"
  fi
else
  : >"$UP_KEYS_FILE"
fi

# Duration dual-keys: public snapshot uses human form; load accepts *_seconds aliases.
ALIASES_NOTE='| Alias / dual form | Canonical public | Notes |
|------------------|------------------|-------|
| `cleanup_after_seconds` | `cleanup_after` | human duration in public map |
| `quarantine_retain_for_seconds` | `quarantine_retain_for` | human duration in public map |
| `stage_archive_to` | `archives_dir` | legacy load alias |
| `mount_backend` aliases `ratarmount` / `ratarmount-rs` | `python` / `rust` | normalized on load |'

{
  echo "# Config key inventory"
  echo
  echo "Generated by \`tools/parity/gen_config_keys.sh\` using \`config.PublicKeys()\`."
  echo
  echo "- **mount-wrapper root:** repo root (script: \`tools/parity/gen_config_keys.sh\`)"
  echo "- **Upstream:** $UPSTREAM_NOTE"
  echo "- **Date (UTC):** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "- **Source of truth:** \`internal/config.ToPublicMap\` / Appendix D in \`TODO.md\`"
  echo
  echo "## mount-wrapper public keys (\`config.PublicKeys\`)"
  echo
  echo "| Key |"
  echo "|-----|"
  while IFS= read -r k; do
    [[ -z "$k" ]] && continue
    echo "| \`$k\` |"
  done <"$GO_KEYS_FILE"
  echo
  echo "### Count"
  echo
  echo "- Public keys: **$(grep -c . "$GO_KEYS_FILE" || true)**"
  echo
  echo "## Load aliases / dual forms (not all in public map)"
  echo
  echo "$ALIASES_NOTE"
  echo
  if [[ -s "$UP_KEYS_FILE" ]]; then
    echo "## Diff vs upstream Config field names"
    echo
    echo "_Heuristic: upstream dataclass / path keys from \`config.py\`. Not every Python attribute is a public YAML key._"
    echo
    echo "### In upstream parse only (may include non-public attrs)"
    echo
    only_up=0
    while IFS= read -r k; do
      [[ -z "$k" ]] && continue
      if ! grep -qxF "$k" "$GO_KEYS_FILE"; then
        # skip known dual forms that map to public human keys
        case "$k" in
          cleanup_after_seconds|quarantine_retain_for_seconds) continue ;;
        esac
        echo "- \`$k\`"
        only_up=1
      fi
    done <"$UP_KEYS_FILE"
    [[ $only_up -eq 0 ]] && echo "_(none — or all covered)_"
    echo
    echo "### In mount-wrapper public only"
    echo
    only_go=0
    while IFS= read -r k; do
      [[ -z "$k" ]] && continue
      if ! grep -qxF "$k" "$UP_KEYS_FILE"; then
        echo "- \`$k\`"
        only_go=1
      fi
    done <"$GO_KEYS_FILE"
    [[ $only_go -eq 0 ]] && echo "_(none)_"
  else
    echo "## Upstream keys"
    echo
    echo "_Skipped — no upstream key list._"
  fi
  echo
  echo "## Notes"
  echo
  echo "- Path defaults rename: \`/…/tarmount-wsl\` → \`/…/mount-wrapper\` (D10)."
  echo "- Schema version remains \`version: 1\`."
  echo "- Hot vs restart classification: \`HotReloadKeys\` / \`RestartRequiredKeys\` in \`internal/config/public.go\`."
} >"$OUT"

echo "Wrote $OUT" >&2
