#!/usr/bin/env bash
# Inventory control-socket ops: mount-wrapper HandleRequest vs upstream service.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
UPSTREAM="${TARMOUNT_WSL_ROOT:-$ROOT/../tarmount-wsl}"
OUT_DIR="${PARITY_OUT:-$ROOT/tools/parity}"
OUT="$OUT_DIR/socket_ops.md"
mkdir -p "$OUT_DIR"

GO_OPS_FILE="$(mktemp)"
UP_OPS_FILE="$(mktemp)"
trap 'rm -f "$GO_OPS_FILE" "$UP_OPS_FILE"' EXIT

# Ops from Service.HandleRequest switch (authoritative).
CONTROL_GO="$ROOT/internal/service/control_ops.go"
if [[ ! -f "$CONTROL_GO" ]]; then
  echo "missing $CONTROL_GO" >&2
  exit 1
fi

grep -E '^\s+case "[a-z_]+":' "$CONTROL_GO" \
  | sed -E 's/.*case "([a-z_]+)".*/\1/' \
  | sort -u >"$GO_OPS_FILE"

UPSTREAM_NOTE="sibling tarmount-wsl **not found** (default \`../tarmount-wsl\`) — Go-side only."
if [[ -d "$UPSTREAM" ]]; then
  UPSTREAM_NOTE="compared against sibling \`../tarmount-wsl\` (or \`TARMOUNT_WSL_ROOT\`)"
  SVC=""
  for cand in \
    "$UPSTREAM/src/tarmount_wsl/service.py" \
    "$UPSTREAM/tarmount_wsl/service.py"; do
    if [[ -f "$cand" ]]; then
      SVC="$cand"
      break
    fi
  done
  if [[ -n "$SVC" ]]; then
    grep -oE 'op\s*==\s*["'"'"'][a-z_]+' "$SVC" \
      | sed -E 's/.*["'"'"']([a-z_]+)/\1/' \
      | sort -u >"$UP_OPS_FILE"
  else
    UPSTREAM_NOTE="sibling present but service.py not found"
    : >"$UP_OPS_FILE"
  fi
else
  : >"$UP_OPS_FILE"
fi

# Known request field notes (static; protocol D6 = new only).
{
  echo "# Socket ops inventory"
  echo
  echo "Generated by \`tools/parity/socket_ops.sh\`."
  echo
  echo "- **mount-wrapper root:** repo root (script: \`tools/parity/socket_ops.sh\`)"
  echo "- **Upstream:** $UPSTREAM_NOTE"
  echo "- **Date (UTC):** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "- **Protocol (D6):** **new protocol only** — framing newline-delimited JSON, \`"v": 1\`; familiar op names where practical; **no dual-daemon / dual-protocol guarantee**."
  echo
  echo "## mount-wrapper ops (\`Service.HandleRequest\`)"
  echo
  echo "| Op | Typical params | Role |"
  echo "|----|----------------|------|"
  while IFS= read -r op; do
    [[ -z "$op" ]] && continue
    params="—"
    role=""
    case "$op" in
      status) params='include_sizes?'; role="Rich status payload" ;;
      metrics) params='archive_id?, no_cache?, prefer_mount?'; role="Size / space-saved metrics" ;;
      config_get) params="—"; role="Public config snapshot" ;;
      config_set) params='config|patch, apply?'; role="Validate / apply config" ;;
      rescan) params='assume_stable?'; role="Immediate source scan" ;;
      retry) params='archive_id'; role="Reset mount attempts / requeue" ;;
      mount) params='path|archive_id'; role="Request mount" ;;
      unmount) params='target|archive_id|all'; role="Unmount one or all" ;;
      purge) params='archive_id, yes'; role="Admin purge (requires confirm)" ;;
      stop) params="—"; role="Graceful serve shutdown" ;;
      reload) params="—"; role="Request config reload" ;;
      hooks_list) params="—"; role="List hooks.d executables" ;;
      hooks_status) params='archive_id'; role="Per-archive hooks rows/status" ;;
    esac
    echo "| \`$op\` | $params | $role |"
  done <"$GO_OPS_FILE"
  echo
  echo "### Framing / auth (summary)"
  echo
  echo "- Newline-delimited JSON request/response"
  echo "- Request: \`{\"v\":1,\"op\":\"…\",…}\` (missing \`v\` treated as 1)"
  echo "- Response OK: \`{\"ok\":true,…}\` / error: \`{\"ok\":false,\"error\":\"…\",\"code\":\"…\"}\`"
  echo "- Auth: peercred root **or** group \`mount-wrapper\`; escape hatch \`MOUNT_WRAPPER_CONTROL_ALLOW_UNAUTH\`"
  echo "- Socket path default: \`/run/mount-wrapper/control.sock\` (macOS under Caches)"
  echo
  if [[ -s "$UP_OPS_FILE" ]]; then
    echo "## Upstream ops (parsed from service.py)"
    echo
    echo "| Op |"
    echo "|----|"
    while IFS= read -r op; do
      [[ -z "$op" ]] && continue
      echo "| \`$op\` |"
    done <"$UP_OPS_FILE"
    echo
    echo "## Diff"
    echo
    echo "### In upstream only"
    echo
    only_up=0
    while IFS= read -r op; do
      [[ -z "$op" ]] && continue
      if ! grep -qxF "$op" "$GO_OPS_FILE"; then
        echo "- \`$op\`"
        only_up=1
      fi
    done <"$UP_OPS_FILE"
    [[ $only_up -eq 0 ]] && echo "_(none)_"
    echo
    echo "### In mount-wrapper only"
    echo
    only_go=0
    while IFS= read -r op; do
      [[ -z "$op" ]] && continue
      if ! grep -qxF "$op" "$UP_OPS_FILE"; then
        echo "- \`$op\`"
        only_go=1
      fi
    done <"$GO_OPS_FILE"
    [[ $only_go -eq 0 ]] && echo "_(none)_"
  else
    echo "## Upstream ops"
    echo
    echo "_Skipped — no upstream inventory._"
  fi
  echo
  echo "## D6 cutover note"
  echo
  echo "Operators must **not** point a tarmount-wsl CLI at a mount-wrapper socket (or vice versa)."
  echo "Op names are intentionally familiar, but auth group, paths, error codes, and payload"
  echo "shapes follow mount-wrapper only. See [docs/migration.md](../../docs/migration.md)."
} >"$OUT"

echo "Wrote $OUT" >&2
